// astro-template/src/components/CartPage.vue
<script setup lang="ts">
import { ref, computed } from 'vue';
import { getCart, saveCart } from '../lib/cart';
import type { Product } from '../lib/products';

const props = defineProps<{ products: Product[] }>();

const cart = ref(getCart());

const cartItems = computed(() =>
  cart.value
    .map(item => {
      const product = props.products.find(p => p.id === item.id);
      return product ? { ...item, product } : null;
    })
    .filter(Boolean) as Array<{ id: number; qty: number; product: Product }>
);

const total = computed(() =>
  cartItems.value.reduce((sum, item) => sum + item.product.price * item.qty, 0)
);

const totalItems = computed(() =>
  cart.value.reduce((sum, item) => sum + item.qty, 0)
);

function formatPrice(n: number) {
  return n.toFixed(2) + '€';
}

function changeQty(id: number, delta: number) {
  const updated = cart.value
    .map(i => i.id === id ? { ...i, qty: i.qty + delta } : i)
    .filter(i => i.qty > 0);
  saveCart(updated);
  cart.value = updated;
}

function remove(id: number) {
  const updated = cart.value.filter(i => i.id !== id);
  saveCart(updated);
  cart.value = updated;
}

function checkout() {
  alert('Checkout is not implemented in this demo.');
}
</script>

<template>
  <div class="cart-header">
    <h1>Shopping Cart</h1>
    <span v-if="totalItems > 0" class="cart-count">
      {{ totalItems }} item{{ totalItems !== 1 ? 's' : '' }} in your cart
    </span>
  </div>

  <div v-if="cartItems.length === 0">
    <p class="muted">Your cart is empty. <a href="/products">Continue shopping</a></p>
  </div>

  <div v-else>
    <table>
      <thead>
        <tr>
          <th>Product</th>
          <th>Price</th>
          <th>Quantity</th>
          <th>Total</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="item in cartItems" :key="item.id">
          <td>
            <a :href="`/products/${item.product.id}`" class="product-link">
              <img :src="item.product.image" :alt="item.product.name" class="thumb" />
              <span class="product-name">{{ item.product.name }}</span>
            </a>
          </td>
          <td>{{ formatPrice(item.product.price) }}</td>
          <td>
            <div class="qty-ctrl">
              <button class="qty-btn" @click="changeQty(item.id, -1)">−</button>
              <span>{{ item.qty }}</span>
              <button class="qty-btn" @click="changeQty(item.id, 1)">+</button>
            </div>
          </td>
          <td>{{ formatPrice(item.product.price * item.qty) }}</td>
          <td>
            <button class="btn btn-danger remove-btn" @click="remove(item.id)">Remove</button>
          </td>
        </tr>
      </tbody>
    </table>

    <div class="summary">
      <span>Total</span>
      <strong>{{ formatPrice(total) }}</strong>
    </div>

    <div class="actions">
      <a href="/products" class="btn btn-outline">Continue shopping</a>
      <button class="btn btn-primary" @click="checkout">Proceed to checkout</button>
    </div>
  </div>
</template>

// next-template/app/components/CartPage.tsx
"use client";
import Link from "next/link";
import { useState, useEffect } from "react";
import type { Product } from "../lib/products";
import type { CartItem } from "../lib/cart";
import { getCart, saveCart } from "../lib/cart";

function formatPrice(n: number) {
  return n.toFixed(2) + "€";
}

export default function CartPage({ products }: { products: Product[] }) {
  const [cart, setCart] = useState<CartItem[]>([]);

  useEffect(() => {
    setCart(getCart());
  }, []);

  function updateCart(newCart: CartItem[]) {
    saveCart(newCart);
    setCart([...newCart]);
  }

  function remove(id: number) {
    updateCart(cart.filter((i) => i.id !== id));
  }

  function changeQty(id: number, action: "inc" | "dec") {
    const updated = cart
      .map((i) => i.id === id ? { ...i, qty: i.qty + (action === "inc" ? 1 : -1) } : i)
      .filter((i) => i.qty > 0);
    updateCart(updated);
  }

  const totalItems = cart.reduce((s, i) => s + i.qty, 0);
  const total = cart.reduce((s, item) => {
    const product = products.find((p) => p.id === item.id);
    return s + (product ? product.price * item.qty : 0);
  }, 0);

  return (
    <>
      <div className="cart-header">
        <h1>Shopping Cart</h1>
        {totalItems > 0 && (
          <span className="cart-count">{totalItems} item{totalItems !== 1 ? "s" : ""} in your cart</span>
        )}
      </div>

      {cart.length === 0 ? (
        <p className="muted">Your cart is empty. <Link href="/products">Continue shopping</Link></p>
      ) : (
        <>
          <table>
            <thead>
              <tr>
                <th>Product</th><th>Price</th><th>Quantity</th><th>Total</th><th></th>
              </tr>
            </thead>
            <tbody>
              {cart.map((item) => {
                const product = products.find((p) => p.id === item.id);
                if (!product) return null;
                return (
                  <tr key={item.id}>
                    <td>
                      <Link href={`/products/${product.id}`} className="product-link">
                        <img src={product.image} alt={product.name} className="thumb" />
                        <span className="product-name">{product.name}</span>
                      </Link>
                    </td>
                    <td>{formatPrice(product.price)}</td>
                    <td>
                      <div className="qty-ctrl">
                        <button className="qty-btn" onClick={() => changeQty(item.id, "dec")}>−</button>
                        <span>{item.qty}</span>
                        <button className="qty-btn" onClick={() => changeQty(item.id, "inc")}>+</button>
                      </div>
                    </td>
                    <td>{formatPrice(product.price * item.qty)}</td>
                    <td>
                      <button className="btn btn-danger" onClick={() => remove(item.id)}>Remove</button>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
          <div className="summary">
            <span>Total</span>
            <strong>{formatPrice(total)}</strong>
          </div>
          <div className="actions">
            <Link href="/products" className="btn btn-outline">Continue shopping</Link>
            <button className="btn btn-primary" onClick={() => alert("Checkout is not implemented in this demo.")}>
              Proceed to checkout
            </button>
          </div>
        </>
      )}
    </>
  );
}
